### ISSUE TITLE
[Feat] 온보딩 전체 로직 체크 및 리펙토링(1)

### ISSUE THREAD

**Issue by Jiseok97** [TEAM-PLAYTOGETHER/PlayTogether_iOS#128]
### 🔥 이슈 주제
- 온보딩 이동이 전반적으로 안 된 부분들이 있어서 수정 예정
- 간단한 코드 리펙토링 예정

### 📝 TODO
- [X] 동아리명 정규식 수정
- [X] 동아리명 입력 View → 자기소개 입력 View 넘어갈 때 로직 수정(동아리명 바인딩 X)
- [X] 자기소개 입력 View `다음`버튼 활성화 로직 수정
- [X] 자기소개 입력 후 넘어가는 로직(서버) 코드 리펙토링
- [X] 자기소개 지하철 데이터 [0개, 1개, 2개] 각각 버튼 활성화 및 API 성공하는지 체크
- [X] 개설완료 View 뒤로가기 기능 추가
